# Copyright (C) 2019 NVIDIA Corporation.  All rights reserved.
# Licensed under the CC BY-NC-SA 4.0 license
# (https://creativecommons.org/licenses/by-nc-sa/4.0/legalcode).

# logger options
image_save_iter: 1500         # How often do you want to save output images during training
snapshot_save_iter: 5000      # How often do you want to save trained models
log_iter: 1                   # How often do you want to log the training stats

# optimization options
max_iter: 200000              # maximum number of training iterations
weight_decay: 0.0001          # weight decay
lr_gen: 0.0001                # learning rate for the generator
lr_dis: 0.0001                # learning rate for the discriminator
init: kaiming                 # initialization [gaussian/kaiming/xavier/orthogonal]
gan_w: 1                      # weight of adversarial loss for image translation
fm_w: 1                       # weight on distance between gan features of style and translated image
r_w: 0.1                      # weight of image reconstruction loss

# model options
gen:
  mel_d : 128                 # dimension of input for content model(n_mel)
  kernel : 5                  # conv1d kernel size
  num_classes: 4              # dimension of the class for the class model(training set)
  latent_dim : 64            # style code
  ch : 64                     # channel in class model encoder
  content_dim : 6             # content code
dis:
  nf: 64                      # base number of filters
  n_res_blks: 8              # number of residual blocks in the discriminator
  num_classes: 4              # dimension of the class for the class model(training set)

# data options
num_workers: 0      ##################
batch_size: 6
data_train: ./datasets/npy_txt/hung/2s_4class_128(no_normalize)/train
label_train: ./datasets/npy_txt/hung/2s_4class_128(no_normalize)/train
data_test: ./datasets/npy_txt/hung/2s_4class_128(no_normalize)/test
label_test: ./datasets/npy_txt/hung/2s_4class_128(no_normalize)/test

# pre-train/fine-tune options
style_pt: ./pre_ckpt/un_normalize_128/style/style_best_263.pt
content_pt: ./pre_ckpt/un_normalize_128/content/content_019_en_best.pt
fine_tune: True

# inference options
outpath: recons_output         # test output path
source: test_audio/01_01.mp3   # source wave path
target: test_audio/01_01.mp3   # target wave path
model: outputs/funit_music_no_D_0423/checkpoints  # model ckpt
